version: '3.7'

services:
  superchain:
    build: .
    entrypoint: ["sh"]
    volumes:
      - .:/home/superchain
      - /home/superchain/node_modules
    networks:
      - superchain-network

networks:
  superchain-network:
    driver: bridge

volumes:
  superchain-data:
